version: '3'
services:
  web:
    build:
      context: .
      args:
        JAR_FILE: target/kubeboot-0.0.1-SNAPSHOT.jar
    ports:
      - "9999:8080"
    environment:
      - SPRING_REDIS_HOST=keyvalue

  keyvalue:
    image: "redis:alpine"
    ports:
      - "6379:6379"
